### ISSUE TITLE
Options menu items (Milestone 1)

### ISSUE THREAD

**Issue by kbrimm** [kbrimm/DrinkToken#14]
- [x] Bug Report selection in Options menu
  - [x] Creates and email for user to submit bug report
- [x] About selection in Options menu
  - [x] Displays license and version information.

**Comment by kbrimm** [comment]
Addressed in PR #18.
