### ISSUE TITLE
Settings menu allows user to clear data  (Milestone 1)

### ISSUE THREAD

**Issue by kbrimm** [kbrimm/DrinkToken#2]
- [x] "Reset Data" selection in settings menu.
- [ ] Selecting "Reset Data" prompts for user confirmation - "Are you sure you want to do this? Action cannot be undone."
- [ ] Data is deleted from app database.

**Comment by kbrimm** [comment]
Addressed in PR #13.
