### ISSUE TITLE
Weekly activity report (Milestone 2)

### ISSUE THREAD

**Issue by kbrimm** [kbrimm/DrinkToken#6]
- [ ] View supplies a comparison of current week's intake vs. historical averages:
  - [ ] Bar graph representing current week's intake, broken out by day of week.
  - [ ] Line graph representing average intake per day of week.
- [ ] New DbHelper methods supply data for report.
- [ ] View is static - no panning/zooming permitted.
- [ ] View scales in response to screen resolution, promotes readability on all screen sizes.
