### ISSUE TITLE
28-day daily intake report (Milestone 2)

### ISSUE THREAD

**Issue by kbrimm** [kbrimm/DrinkToken#7]
- [ ] Report supplies a view of consumption trends for past 28 days.
- [ ] New DbHelper methods supply data for report.
- [ ] View may be dynamic - user can pan across length of view.
- [ ] View scales in response to screen resolution, promotes readability on all screen sizes.
