### ISSUE TITLE
One-year weekly intake report (Milestone 2)

### ISSUE THREAD

**Issue by kbrimm** [kbrimm/DrinkToken#8]
- [ ] Report supplies a view of consumption per week over the last 52 weeks.
- [ ] New DbHelper methods supply data for report.
- [ ] View is dynamic - user is able to pan across view.
- [ ] View scales in response to screen resolution, promotes readability on all screen sizes.
