### ISSUE TITLE
Dashboard correctly displays counts and averages (Milestone 1)

### ISSUE THREAD

**Issue by kbrimm** [kbrimm/DrinkToken#9]
- [x] Count increments correctly
- [x] Count limited to correct time window
- [x] Averages calculate correctly

**Comment by kbrimm** [comment]
This just requires a few days of run-time testing, and it should be good to go.

**Comment by kbrimm** [comment]
Addressed in PR #16.
